### ISSUE TITLE
South African keyboard layout (za) for languages nso, ve, tn

### ISSUE THREAD

**Issue by friedelwolff** [mike-fabian/langtable#10]
The South African languages Northern Sotho (nso), Tswana (tn) and Venda (ve) need the South African keyboard layout ("za"  - a variant of en_US).

**Comment by friedelwolff** [comment]
I forgot to add: the language Afrikaans (af) can also be typed with this keyboard layout, although it wouldn't be my recommendation.

**Comment by mike-fabian** [comment]
This should fix both https://github.com/mike-fabian/langtable/issues/9 and https://github.com/mike-fabian/langtable/issues/10

https://github.com/mike-fabian/langtable/commits/release-0.0.45
