### ISSUE TITLE
Common locales

### ISSUE THREAD

**Issue by VladimirSlavik** [mike-fabian/langtable#15]
Hello Mike, could you please extend the api with a counterpart to `list_common_languages`, a new function that would return the underlying locales?

CC @OndrejZobal

**Comment by mike-fabian** [comment]
Yes!

How should it be called and what should it return?

`list_common_locales`?

```python
>>> langtable.list_common_languages()
['ar', 'en', 'fr', 'de', 'ja', 'zh', 'ru', 'es']
```

Should `list_common_locales()` return the locales for all of these?

**Comment by mike-fabian** [comment]
Should it return a short list like

```
en_US.UTF-8 en_GB.UTF-8 de_DE.UTF-8 fr_FR.UTF-8 es_ES.UTF-8 zh_CN.UTF-8 ja_JP.UTF-8 ru_RU.UTF-8 ar_EG.UTF-8
```

or should it return all possible glibc locales for these languages?

For Arabic alone there are 19:

```
$ locale -a | grep ^ar | grep utf8
ar_AE.utf8
ar_BH.utf8
ar_DZ.utf8
ar_EG.utf8
ar_IN.utf8
ar_IQ.utf8
ar_JO.utf8
ar_KW.utf8
ar_LB.utf8
ar_LY.utf8
ar_MA.utf8
ar_OM.utf8
ar_QA.utf8
ar_SA.utf8
ar_SD.utf8
ar_SS.utf8
ar_SY.utf8
ar_TN.utf8
ar_YE.utf8
```

**Comment by OndrejZobal** [comment]
`list_common_locales` sounds like a good name.
The function should return the most common locale for the most common languages, in other words the short list you suggested:
> `en_US.UTF-8 en_GB.UTF-8 de_DE.UTF-8 fr_FR.UTF-8 es_ES.UTF-8 zh_CN.UTF-8 ja_JP.UTF-8 ru_RU.UTF-8 ar_EG.UTF-8`

Thanks for being so active btw.

**Comment by VladimirSlavik** [comment]
I actually wonder - do we (well, gnome) know the most common locales, or just languages?

**Comment by mike-fabian** [comment]
> `list_common_locales` sounds like a good name. The function should return the most common locale for the most common languages, in other words the short list you suggested:
> 
> > `en_US.UTF-8 en_GB.UTF-8 de_DE.UTF-8 fr_FR.UTF-8 es_ES.UTF-8 zh_CN.UTF-8 ja_JP.UTF-8 ru_RU.UTF-8 ar_EG.UTF-8`
> 
> Thanks for being so active btw.

Ah, OK, I will do that then!

**Comment by mike-fabian** [comment]
> I actually wonder - do we (well, gnome) know the most common locales, or just languages? I did not realize earlier, but the `ar_EG` in gnome's list might be simply an artifact of "let's pick one of the Arabic locales since the next function consumes locales", instead of "Arabic/Egypt is among the most common locales".

Yes, I think you are right that Gnome just picked one of the locales randomly.

I’ll make a function list_common_locales and think about it a bit more, maybe check the population of countries, but making a short list of the really common locales seems to be much more useful then just listing **all** locales for the common languages, this would be already easy with the current API:

>>> langtable.list_locales(languageId='ar')
['ar_EG.UTF-8', 'ar_SD.UTF-8', 'ar_DZ.UTF-8', 'ar_MA.UTF-8', 'ar_IQ.UTF-8', 'ar_SA.UTF-8', 'ar_YE.UTF-8', 'ar_SY.UTF-8', 'ar_TN.UTF-8', 'ar_LY.UTF-8', 'ar_JO.UTF-8', 'ar_AE.UTF-8', 'ar_LB.UTF-8', 'ar_KW.UTF-8', 'ar_OM.UTF-8', 'ar_QA.UTF-8', 'ar_BH.UTF-8', 'ar_IN.UTF-8', 'ar_SS.UTF-8']

So if `list_common_locales` just did that for all common languages, it would be a bit pointless, a short list of common locales seems to be better as the result of `list_common_locales`.

I will do that tomorrow.

**Comment by mike-fabian** [comment]
Fixed in 0.0.60:
```
$ python3
Python 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import langtable
>>> langtable.version()
'0.0.60'
>>> langtable.list_common_languages()
['ar', 'en', 'fr', 'de', 'ja', 'zh', 'ru', 'es']
>>> langtable.list_common_locales()
['ar_EG.UTF-8', 'en_US.UTF-8', 'en_GB.UTF-8', 'fr_FR.UTF-8', 'de_DE.UTF-8', 'ja_JP.UTF-8', 'zh_CN.UTF-8', 'ru_RU.UTF-8', 'es_ES.UTF-8']
>>> 
```

**Comment by mike-fabian** [comment]
The lists are not sorted. The output of `langtable.list_common_languages()` was not sorted alphabetically and not sorted by the number of language users either.

So I didn’t sort the output of `langtable.list_common_locales()` either.

The order of the output of `langtable.list_common_locales()` is currently always in the same arbitrary order as `langtable.list_common_languages()`. For each language, multiple locales may be listed (Curently there are two for 'en', 'en_US.UTF-8' and 'en_GB.UTF-8',  for the other languages there is currently only one).

I could sort the lists in other ways if desired and I could also tweak the output more if desired.

**Comment by OndrejZobal** [comment]
I think, this is fine. Thank you very much!
