### ISSUE TITLE
Esperanto is not findable through langtable

### ISSUE THREAD

**Issue by carmenbianca** [mike-fabian/langtable#6]
Dear maintainer,

Bug report can be summarised through a few lines of code:

```
$ python3
>>> import langtable
>>> langtable.list_locales(languageId='eo')
[]
>>> exit()
$ locale -a | grep eo
eo
```

Expected result is `['eo.UTF-8']`.

Tested on Fedora 29 and Fedora Rawhide. Related to <https://bugzilla.redhat.com/show_bug.cgi?id=1652708>.

See also <https://sourceware.org/bugzilla/show_bug.cgi?id=23857> for issues surrounding Esperanto/glibc, and a possible cause for the issue.

Thanks!

**Comment by mike-fabian** [comment]
Thank you! Included in: https://github.com/mike-fabian/langtable/releases/tag/0.0.40
